# Generated by Django 4.2 on 2023-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('article', models.TextField(verbose_name='Статья')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
        ),
    ]
